version: '3.9'

services:
  web:
    build: .
    container_name: dockproj-web
    # command: python manage.py runserver 0.0.0.0:8001
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings
