# Generated by Django 5.2.7 on 2025-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проектов')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Название проектов дo 1')),
            ],
        ),
    ]
